import Head from 'next/head'
import { Main } from 'styles/WorkingComponentStyle'
import Image from 'next/image'
import logoEnglish from 'assets/img/Logo-Colorida-1.webp'
import logo from 'assets/img/u.webp'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Main>
        <div>
          <h1>we&apos;re working</h1>
          <Image src={logo} alt="English 101" />
          <Image src={logoEnglish} alt="Underground Devs" />
        </div>
      </Main>
    </>
  )
}
