import Head from 'next/head'
import { Main } from 'styles/WorkingComponentStyle'
import Image from 'next/image'
import logo from 'assets/img/Logo.png'
import logoUnderground from 'assets/img/underground-slogan.png'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Main>
        <div>
          <h1>we&apos;re working</h1>
          <Image src={logoUnderground} alt="Underground Devs" />
          <Image src={logo} alt="English 101" />
        </div>
      </Main>
    </>
  )
}
