import { Main } from 'styles/WorkingComponentStyle'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Main>
        <div>
          <h1>we&apos;re working</h1>
          <div className="photo">
            <Image
              src="/Logo-Colorida-1.webp"
              alt="English 101"
              width={216}
              height={89}
            />
          </div>
          <div className="photo">
            <Image
              src="/u.webp"
              alt="Underground Devs"
              width={848}
              height={1098}
            />
          </div>
        </div>
      </Main>
    </>
  )
}

export default Home;