import { Main } from 'styles/WorkingComponentStyle'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Main>
        <div>
          <h1>we&apos;re working</h1>
          <div className="photo">
            <img
              src="/Logo-Colorida-1.webp"
              alt="English 101"
            />
          </div>
          <div className="photo">
            <img
              src="/u.webp"
              alt="Underground Devs"
            />
          </div>
        </div>
      </Main>
    </>
  )
}

export default Home;